apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-myservice
          image: nginx:1.14.2
          command: ['sh', '-c', "echo $MY_NODE_NAME Deployment2 > /usr/share/nginx/html/index.html"]
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: cache-volume
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}
      nodeSelector:
        mtd/node: active